[theme]
base="light"
primaryColor="#1E88E5"
backgroundColor="#FAFAFA"
secondaryBackgroundColor="#FFFFFF"
textColor="#212121"
font="sans serif"

[server]
headless = true
enableCORS = false
port = 8080
